public class Constants {

    
    public static String STATUS_SHIPPED = 'Shipped';
    public static String STATUS_DRAFT = 'Draft';
    public static String STATUS_ACTIVATED = 'Activated';
  
   
    public static final String ORDERID_EMPTY = 'orderIds cannot be empty!';
    public static final String PAGESIZE_NULL = 'pageSize cannot be null!';
    public static final String NULL_ORDERIDS = 'Null OrderIds';


    public static String INVALID_ACCOUNT = 'Not a valid Account Id';
    public static String INVALID_ORDER_ID = 'Not a valid Order Id';

    public static final String ORDER_UPDATE_STATUS_OK = 'OK';
    public static final String ORDER_UPDATE_STATUS_ERROR = 'ERROR';

    public static final String NO_ORDER_TO_PROCESS = 'No orders to Process';

    public static final String NULL_LAST_STATUS_CHANGED = 'LastStatusChanged is Null';
    
}